language: node_js
node_js:
  - "lts/*"

script:
  - npm test

before_deploy: |
  function npm_dist_tag() {
    if [[ "$TRAVIS_TAG" = *"-"* ]]; then
      echo "beta"
    else
      echo "latest"
    fi
  }

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "lts/*"
      script: ./scripts/build.sh
      before_deploy:
        cd ./tmp/package
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        tag: $(npm_dist_tag)
        on:
          tags: true
